name: Idea
description: Something YT Notch could do.
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like it to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would it help?
